name: MewEconomy
main: co.mcsky.meweconomy.MewEconomy
version: ${version}
api-version: 1.13
author: Nailm
website: https://mimaru.me
depend: [ MoeCore, Vault, helper, Essentials, Towny, ChestShop ]
softdepend: [ PlaceholderAPI ]